import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateInvoicePDF(invoice, items) {

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // ===========================
  // Company
  // ===========================

  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("BusinessOS Technologies", 14, 18);

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");

  pdf.text("Lahore, Punjab, Pakistan", 14, 24);
  pdf.text("support@businessos.pk", 14, 29);
  pdf.text("+92 300 1234567", 14, 34);

  // ===========================
  // Invoice Info
  // ===========================

  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");

  pdf.text("INVOICE", 150, 18);

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");

  pdf.text(
    `Invoice: ${invoice.invoice_no}`,
    150,
    26
  );

  pdf.text(
    `Date: ${new Date(
      invoice.created_at
    ).toLocaleDateString()}`,
    150,
    31
  );

  pdf.text(
    `Status: ${invoice.status}`,
    150,
    36
  );

  // ===========================
  // Customer
  // ===========================

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");

  pdf.text("Bill To", 14, 48);

  pdf.setFont("helvetica", "normal");

  pdf.text(
    invoice.customers?.full_name || "",
    14,
    54
  );

  // ===========================
  // Table
  // ===========================

  const rows = items.map((item) => [

    item.products?.product_name,

    item.quantity,

    `PKR ${Number(item.price).toLocaleString()}`,

    `PKR ${Number(item.cost_price).toLocaleString()}`,

    `PKR ${Number(item.total_profit).toLocaleString()}`,

    `PKR ${Number(item.total).toLocaleString()}`,

  ]);

 autoTable(pdf, {

  startY: 65,

  head: [[
    "Product",
    "Qty",
    "Price",
    "Cost",
    "Profit",
    "Total",
  ]],

  body: rows,

  theme: "grid",


    styles: {

      fontSize: 9,

    },

    headStyles: {

      fillColor: [37, 99, 235],

    },

  });

  // ===========================
  // Grand Total
  // ===========================

  const finalY =
  (pdf.lastAutoTable?.finalY || 65) + 10;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);

  pdf.text(

    `Grand Total: PKR ${Number(
      invoice.total
    ).toLocaleString()}`,

    130,

    finalY

  );

  // ===========================
  // Footer
  // ===========================

  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");

  pdf.text(

    "Generated by BusinessOS",

    14,

    285

  );

  pdf.save(

    `Invoice-${invoice.invoice_no}.pdf`

  );

}